// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get the environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://efumbahvpnxnuoojwrdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdW1iYWh2cG54bnVvb2p3cmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTAxNjgsImV4cCI6MjA2MzIyNjE2OH0.RfEnNUea4BintAQ_BWMcz6c8qaLuq-a4m7y3ZqH_Slw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log("Initializing Supabase client with URL:", SUPABASE_URL);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
